### ISSUE TITLE
question about the DAE_newmark

### ISSUE THREAD

**Issue by ghost** [rserban/ANCF_beam#2]
In the DAE_newmark.m,  the matrix J which is for the Newton-Rapson iteration ignored the stiffness matrix  compared to the conventional newmark mehtod.
I am wondering if there is any problem.

**Comment by rserban** [comment]
Indeed, what I implemented here is a particular type of quasi-Newton method, in that it uses an approximation of the Jacobian matrix (ignoring certain terms in the full Jacobian which are more cumbersome to compute).  For the problems I was testing with this code, I didn't have any convergence issues.  If you experience any, you may want to implement the full Jacobian and hence an exact Newton method.

**Comment by ghost** [comment]
got it, thank you
